# Generated by Django 2.2.10 on 2021-03-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210228_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='anggota',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='KalenderKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_program', models.DateField()),
                ('lokasi_program', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('jenis_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramKerja')),
            ],
        ),
    ]
