# Generated by Django 2.2.10 on 2021-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210318_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalenderkerja',
            name='nama',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
