# Generated by Django 2.2.10 on 2021-03-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_kalenderkerja_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kalenderkerja',
            old_name='jenis_program',
            new_name='program',
        ),
    ]
