# Generated by Django 2.2.10 on 2021-03-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jadwaldiskusi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariDiskusi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='jadwaldiskusi',
            name='hari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HariDiskusi'),
        ),
    ]
