# Generated by Django 2.2.10 on 2021-04-01 09:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_event_eventmember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventModel',
        ),
    ]
