# Generated by Django 2.2.10 on 2021-04-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210401_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
    ]
